name: femispace
description: "FemiSpace Task Project"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8

  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # Font
  google_fonts: ^6.2.1

  # For App Logo
  flutter_launcher_icons: ^0.13.1

  # Router
  go_router: ^14.2.6

  # Screen Size Control
  flutter_screenutil: ^5.9.3

  # Native Splash
  flutter_native_splash: ^2.4.1

  # Logger
  logger: ^2.4.0

  # Text Size Control
  auto_size_text: ^3.0.0


  # Animation
  animate_do: ^3.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.12
  riverpod_generator: ^2.4.3
  flutter_lints: ^4.0.0

# App Logo
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_logo.png"


# Native Splash Configure
flutter_native_splash:
  android: true
  ios: true
  web: false
  color: "#ffffff"


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/app_logo.png
